---
# tasks file for myapache
- name: Installing packages
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs }}"

- name: starting services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ pkgs }}"

- name: enabled firewall for http
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ rule }}"
- name: updating web pages
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: restart httpd
